package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/vika2603/ccs/internal/state"
)

// newInstallShimCmd writes ~/.ccs/bin/claude, a small sh script that routes
// to `ccs __shim_exec claude`. The shim embeds the absolute path to the ccs
// binary, so it keeps working even if ccs drops out of PATH.
func newInstallShimCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "install-shim",
		Short: "Install ~/.ccs/bin/claude so `claude` routes through ccs",
		RunE: func(cmd *cobra.Command, _ []string) error {
			_, p, err := manager()
			if err != nil {
				return err
			}
			self, err := os.Executable()
			if err != nil {
				return fmt.Errorf("locate ccs binary: %w", err)
			}
			self, err = filepath.Abs(self)
			if err != nil {
				return fmt.Errorf("resolve ccs binary path: %w", err)
			}
			shim := p.ShimPath("claude")
			if !force {
				if _, err := os.Stat(shim); err == nil {
					return fmt.Errorf("shim already exists at %s (use --force to overwrite)", shim)
				} else if !os.IsNotExist(err) {
					return err
				}
			}
			if err := os.MkdirAll(p.BinDir(), 0o755); err != nil {
				return err
			}
			content := shimScript(self, "claude")
			if err := os.WriteFile(shim, []byte(content), 0o755); err != nil {
				return err
			}
			// os.WriteFile respects umask; chmod explicitly so it is executable.
			if err := os.Chmod(shim, 0o755); err != nil {
				return err
			}
			cmd.Printf("wrote %s\n", shim)
			cmd.Printf("\nAdd %s to PATH. For GUI apps (VS Code, JetBrains) to see it too,\n", p.BinDir())
			cmd.Printf("put this in ~/.zprofile (not just ~/.zshrc):\n\n")
			cmd.Printf("  export PATH=\"%s:$PATH\"\n\n", p.BinDir())
			cmd.Printf("Then reopen the terminal or GUI app. `which claude` should point at %s.\n", shim)
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing shim")
	return cmd
}

func shimScript(ccsPath, target string) string {
	return "#!/bin/sh\n" +
		"# Generated by `ccs install-shim`. Routes `" + target + "` through ccs so\n" +
		"# per-profile env vars reach the " + target + " process without polluting the shell.\n" +
		"exec " + shellQuote(ccsPath) + " __shim_exec " + shellQuote(target) + " \"$@\"\n"
}

// shellQuote wraps s in single quotes with POSIX-safe escaping.
// Kept local to this file to avoid pulling profileenv's ShellQuote into cmd/.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// newInternalShimExecCmd implements `ccs __shim_exec <cmd> [args...]`.
// Called by the ~/.ccs/bin shim. Looks up the active profile and execs the
// target command with profile env injected (via runClaudeForProfile) or
// without (via runClaudePassthrough) if nothing is active.
//
// If CLAUDE_CONFIG_DIR is already set in env, the shim passes through
// without consulting state/active. This matches the shell hook's rule of
// never overwriting a CCD the caller already set, and fixes the case where
// `ccs run <profile>` execs a wrapper like `caffeinate claude` — the wrapper
// resolves `claude` via PATH back to this shim, which would otherwise reset
// CCD from state/active and undo what `ccs run` just configured.
//
// DisableFlagParsing is true because args after the target (e.g. --help,
// --version) belong to the target command, not to ccs.
func newInternalShimExecCmd() *cobra.Command {
	return &cobra.Command{
		Use:                "__shim_exec <cmd> [args...]",
		Hidden:             true,
		DisableFlagParsing: true,
		Args:               cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if os.Getenv("CLAUDE_CONFIG_DIR") != "" {
				return runClaudePassthrough(args)
			}
			_, p, err := manager()
			if err != nil {
				return err
			}
			name, _ := state.Read(p.ActiveFile())
			if name == "" {
				return runClaudePassthrough(args)
			}
			return runClaudeForProfile(name, args)
		},
	}
}
