package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/cobra"

	"github.com/vika2603/ccs/internal/fsutil"
)

// installShim writes ~/.ccs/bin/claude, a small sh script that routes to
// `ccs __shim_exec claude`. The shim embeds the absolute path of the running
// ccs binary, so it keeps working even if ccs drops out of PATH.
func (a app) installShim() (string, error) {
	self, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("locate ccs binary: %w", err)
	}
	self, err = filepath.Abs(self)
	if err != nil {
		return "", fmt.Errorf("resolve ccs binary path: %w", err)
	}
	shim := a.ShimPath("claude")
	// Replace a symlink at the shim path itself; writing through it would
	// overwrite whatever it points to, possibly the real claude binary.
	if info, err := os.Lstat(shim); err == nil && info.Mode()&os.ModeSymlink != 0 {
		if err := os.Remove(shim); err != nil {
			return "", err
		}
	}
	if err := fsutil.WriteFileAtomic(shim, []byte(shimScript(self, "claude")), 0o755); err != nil {
		return "", err
	}
	return shim, nil
}

// onPath reports whether dir is listed in $PATH.
func onPath(dir string) bool {
	return slices.Contains(filepath.SplitList(os.Getenv("PATH")), dir)
}

// shellQuote wraps s in single quotes so sh reads it verbatim.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func shimScript(ccsPath, target string) string {
	return "#!/bin/sh\n" +
		"# Generated by `ccs init`. Routes `" + target + "` through ccs so\n" +
		"# per-profile env vars reach the " + target + " process without polluting the shell.\n" +
		"exec " + shellQuote(ccsPath) + " __shim_exec " + shellQuote(target) + " \"$@\"\n"
}

// newInternalShimExecCmd implements `ccs __shim_exec <cmd> [args...]`.
// Called by the ~/.ccs/bin shim. Looks up the active profile and execs the
// target command with that profile's env injected, or with the parent env
// unchanged if nothing is active.
//
// If CLAUDE_CONFIG_DIR is already set in env, the shim passes through
// without consulting state/active. This matches the shell hook's rule of
// never overwriting a CCD the caller already set, and fixes the case where
// `ccs run <profile>` execs a wrapper like `caffeinate claude` — the wrapper
// resolves `claude` via PATH back to this shim, which would otherwise reset
// CCD from state/active and undo what `ccs run` just configured.
//
// DisableFlagParsing is true because args after the target (e.g. --help,
// --version) belong to the target command, not to ccs.
func newInternalShimExecCmd() *cobra.Command {
	return &cobra.Command{
		Use:                "__shim_exec <cmd> [args...]",
		Hidden:             true,
		DisableFlagParsing: true,
		Args:               cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			a, err := loadApp()
			if err != nil {
				return err
			}
			// CCS_MANAGED_CCD marks a CLAUDE_CONFIG_DIR exported by the shell
			// hook of older ccs releases. It may be stale, so both are dropped
			// and the active profile (or ~/.claude when none) applies.
			if os.Getenv("CCS_MANAGED_CCD") != "" {
				_ = os.Unsetenv("CLAUDE_CONFIG_DIR")
				_ = os.Unsetenv("CCS_MANAGED_CCD")
			}
			if os.Getenv("CLAUDE_CONFIG_DIR") != "" {
				return a.launch("", args)
			}
			name, _ := a.Active()
			return a.launch(name, args)
		},
	}
}
